Vagrant.configure("2") do |config|

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/trusty64"
    web.vm.network :forwarded_port, guest: 80, host: 8088 
    config.vm.provision "shell", path: "script.sh"
  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/trusty64"
    config.vm.boot_timeout = 1000
    config.vm.provision "shell", path: "script2.sh"
    db.vm.network :forwarded_port, guest: 80, host: 8089 
  end
end