Vagrant.configure("2") do |config|
  	#config.vm.box = "v0rtex/xenial64"
    config.vm.box = "kaorimatz/ubuntu-16.04-amd64"

  	config.vm.provider "virtualbox" do |v|
        v.memory = 6000
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
#        v.customize ["devStack", :id, "--natdnshostresolver1", "on"]
    end
  	
    config.vm.network :private_network, ip: "171.168.33.20"
    config.vm.network :forwarded_port, guest: 80, host: 8081 
    config.vm.hostname = "philipDevStack"
    config.vm.provision "shell", path: "script.sh", privileged: false
end
